echo off

SET TABLEFILE=.\FDEOutput\PLAN_MOPP_%4.tbl

echo CALENDAR;1 > %TABLEFILE%
echo ORGANIZATION;2 >> %TABLEFILE%
echo PRODUCT;3 >> %TABLEFILE%
echo ADJ_CST_MOP2;4 >> %TABLEFILE%
echo ADJ_CST_MOPP;5 >> %TABLEFILE%
echo ADJ_UNT_MOP2;6 >> %TABLEFILE%
echo ADJ_UNT_MOPP;7 >> %TABLEFILE%
echo BOP_CST_MOP2;8 >> %TABLEFILE%
echo BOP_CST_MOPP;9 >> %TABLEFILE%
echo BOP_UNT_MOP2;10 >> %TABLEFILE%
echo BOP_UNT_MOPP;11 >> %TABLEFILE%
echo CALBOP_CST_MOP2;12 >> %TABLEFILE%
echo CALBOP_CST_MOPP;13 >> %TABLEFILE%
echo CALBOP_UNT_MOP2;14 >> %TABLEFILE%
echo CALBOP_UNT_MOPP;15 >> %TABLEFILE%
echo CAOTB_CST_MOP2;16 >> %TABLEFILE%
echo CAOTB_CST_MOPP;17 >> %TABLEFILE%
echo CAOTB_UNT_MOP2;18 >> %TABLEFILE%
echo CAOTB_UNT_MOPP;19 >> %TABLEFILE%
echo FRT_CST_MOP2;20 >> %TABLEFILE%
echo FRT_CST_MOPP;21 >> %TABLEFILE%
echo MDPMD_RTL_MOP2;22 >> %TABLEFILE%
echo MDPMD_RTL_MOPP;23 >> %TABLEFILE%
echo MDPOS_RTL_MOP2;24 >> %TABLEFILE%
echo MDPOS_RTL_MOPP;25 >> %TABLEFILE%
echo OTB_CST_MOP2;26 >> %TABLEFILE%
echo OTB_CST_MOPP;27 >> %TABLEFILE%
echo OTB_UNT_MOP2;28 >> %TABLEFILE%
echo OTB_UNT_MOPP;29 >> %TABLEFILE%
echo RECCOM_CST_MOP2;30 >> %TABLEFILE%
echo RECCOM_CST_MOPP;31 >> %TABLEFILE%
echo RECCOM_UNT_MOP2;32 >> %TABLEFILE%
echo RECCOM_UNT_MOPP;33 >> %TABLEFILE%
echo RECNCOM_CST_MOP2;34 >> %TABLEFILE%
echo RECNCOM_CST_MOPP;35 >> %TABLEFILE%
echo RECNCOM_UNT_MOP2;36 >> %TABLEFILE%
echo RECNCOM_UNT_MOPP;37 >> %TABLEFILE%
echo SHR_CST_MOP2;38 >> %TABLEFILE%
echo SHR_CST_MOPP;39 >> %TABLEFILE%
echo SHR_UNT_MOP2;40 >> %TABLEFILE%
echo SHR_UNT_MOPP;41 >> %TABLEFILE%
echo SLSCON_CST_MOP2;42 >> %TABLEFILE%
echo SLSCON_CST_MOPP;43 >> %TABLEFILE%
echo SLSCON_RTL_MOP2;44 >> %TABLEFILE%
echo SLSCON_RTL_MOPP;45 >> %TABLEFILE%
echo SLSCON_UNT_MOP2;46 >> %TABLEFILE%
echo SLSCON_UNT_MOPP;47 >> %TABLEFILE%
echo SLSNXT_EXPC_MOP2;48 >> %TABLEFILE%
echo SLSNXT_EXPC_MOPP;49 >> %TABLEFILE%
echo SLSNXT_EXPU_MOP2;50 >> %TABLEFILE%
echo SLSNXT_EXPU_MOPP;51 >> %TABLEFILE%
echo SLS_CST_MOP2;52 >> %TABLEFILE%
echo SLS_CST_MOPP;53 >> %TABLEFILE%
echo SLS_RTL_MOP2;54 >> %TABLEFILE%
echo SLS_RTL_MOPP;55 >> %TABLEFILE%
echo SLS_UNT_MOP2;56 >> %TABLEFILE%
echo SLS_UNT_MOPP;57 >> %TABLEFILE%
echo SQM_MOP2;58 >> %TABLEFILE%
echo SQM_MOPP;59 >> %TABLEFILE%

sqlplus -L -S %1/%2@%3 @PLAN_MOPP.sql %4

echo %4 > .\FDEOutput\PLAN_MOPP_%4.done