SET HEADING OFF;
SET PAGESIZE 0;
SET WRAP OFF;
SET LINESIZE 10000;
SET TRIMSPOOL ON;
SET TRIMOUT ON;
SET TERMOUT OFF;
SET FEEDBACK OFF;
SPOOL .\FDEOutput\PLAN_STPP_&&1..csv;
SELECT
'"' || CALENDAR || '";' ||
'"' || ORGANIZATION || '";' ||
'"' || PRODUCT || '";' ||
ROUND(AVGINV_CST_STP2,2) || ';' ||
ROUND(AVGINV_CST_STPP,2) || ';' ||
ROUND(GM_STP2,2) || ';' ||
ROUND(GM_STPP,2) || ';' ||
ROUND(SLSCOMP_RTL_STP2,2) || ';' ||
ROUND(SLSCOMP_RTL_STPP,2) || ';' ||
ROUND(SLSNCOMP_RTL_STP2,2) || ';' ||
ROUND(SLSNCOMP_RTL_STPP,2) || ';' ||
ROUND(SLS_CST_STP2,2) || ';' ||
ROUND(SLS_CST_STPP,2) || ';' ||
ROUND(SLS_UNT_STP2,2) || ';' ||
ROUND(SLS_UNT_STPP,2) || '|'
FROM CA_PLAN_STPP_VIEW;
SPOOL OFF;
EXIT;