pkbfdatrm / type=facttables ftf=ACTUAL_INVBAL analyze=n empty=y
pkbfdatrm / type=facttables ftf=ACTUAL_MKDNS analyze=n empty=y
pkbfdatrm / type=facttables ftf=ACTUAL_RECEIPTS analyze=n empty=y
pkbfdatrm / type=facttables ftf=ACTUAL_SALES analyze=n empty=y
pkbfdatrm / type=facttables ftf=ACTUAL_ON_ORDER analyze=n empty=y
pkbfdatrm / type=facttables ftf=ACTUAL_OTHINV analyze=n empty=y
pkbfdatrm / type=facttables ftf=ACTUAL_VA analyze=n empty=y
pkbfdatrm / type=facttables ftf=ACTUAL_LOAD analyze=n empty=y

pkbfdatrm / type=facttables ftf=PL_BUL2 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_BULP analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_BUP1 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_BUP2 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_LL analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_LP analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_MOL2 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_MOLP analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_MOP2 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_MOPP analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_OL analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_OP1 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_RL analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_RP1 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_STP2 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_STPP analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_TDL2 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_TDLP analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_TDP1 analyze=n empty=y
pkbfdatrm / type=facttables ftf=PL_TDP2 analyze=n empty=y