SET HEADING OFF;
SET PAGESIZE 0;
SET WRAP OFF;
SET LINESIZE 10000;
SET TRIMSPOOL ON;
SET TRIMOUT ON;
SET TERMOUT OFF;
SET FEEDBACK OFF;
SPOOL .\FDEOutput\PLAN_BUPP_&&1..csv;
SELECT
'"' || CALENDAR || '";' ||
'"' || ORGANIZATION || '";' ||
'"' || PRODUCT || '";' ||
ROUND(ADJ_CST_BUP1,2) || ';' ||
ROUND(ADJ_CST_BUP2,2) || ';' ||
ROUND(ADJ_CST_LP,2) || ';' ||
ROUND(ADJ_CST_OP1,2) || ';' ||
ROUND(ADJ_CST_RP1,2) || ';' ||
ROUND(ADJ_UNT_BUP1,2) || ';' ||
ROUND(ADJ_UNT_BUP2,2) || ';' ||
ROUND(ADJ_UNT_LP,2) || ';' ||
ROUND(ADJ_UNT_OP1,2) || ';' ||
ROUND(ADJ_UNT_RP1,2) || ';' ||
ROUND(BOP_CST_BUP1,2) || ';' ||
ROUND(BOP_CST_BUP2,2) || ';' ||
ROUND(BOP_CST_LP,2) || ';' ||
ROUND(BOP_CST_OP1,2) || ';' ||
ROUND(BOP_CST_RP1,2) || ';' ||
ROUND(BOP_UNT_BUP1,2) || ';' ||
ROUND(BOP_UNT_BUP2,2) || ';' ||
ROUND(BOP_UNT_LP,2) || ';' ||
ROUND(BOP_UNT_OP1,2) || ';' ||
ROUND(BOP_UNT_RP1,2) || ';' ||
ROUND(CALBOP_CST_BUP1,2) || ';' ||
ROUND(CALBOP_CST_BUP2,2) || ';' ||
ROUND(CALBOP_CST_LP,2) || ';' ||
ROUND(CALBOP_CST_OP1,2) || ';' ||
ROUND(CALBOP_CST_RP1,2) || ';' ||
ROUND(CALBOP_UNT_BUP1,2) || ';' ||
ROUND(CALBOP_UNT_BUP2,2) || ';' ||
ROUND(CALBOP_UNT_LP,2) || ';' ||
ROUND(CALBOP_UNT_OP1,2) || ';' ||
ROUND(CALBOP_UNT_RP1,2) || ';' ||
ROUND(CAOTB_CST_BUP1,2) || ';' ||
ROUND(CAOTB_CST_BUP2,2) || ';' ||
ROUND(CAOTB_CST_LP,2) || ';' ||
ROUND(CAOTB_CST_OP1,2) || ';' ||
ROUND(CAOTB_CST_RP1,2) || ';' ||
ROUND(CAOTB_UNT_BUP1,2) || ';' ||
ROUND(CAOTB_UNT_BUP2,2) || ';' ||
ROUND(CAOTB_UNT_LP,2) || ';' ||
ROUND(CAOTB_UNT_OP1,2) || ';' ||
ROUND(CAOTB_UNT_RP1,2) || ';' ||
ROUND(FRT_CST_BUP1,2) || ';' ||
ROUND(FRT_CST_BUP2,2) || ';' ||
ROUND(FRT_CST_LP,2) || ';' ||
ROUND(FRT_CST_OP1,2) || ';' ||
ROUND(FRT_CST_RP1,2) || ';' ||
ROUND(MDPMD_RTL_BUP1,2) || ';' ||
ROUND(MDPMD_RTL_BUP2,2) || ';' ||
ROUND(MDPMD_RTL_LP,2) || ';' ||
ROUND(MDPMD_RTL_OP1,2) || ';' ||
ROUND(MDPMD_RTL_RP1,2) || ';' ||
ROUND(MDPOS_RTL_BUP1,2) || ';' ||
ROUND(MDPOS_RTL_BUP2,2) || ';' ||
ROUND(MDPOS_RTL_LP,2) || ';' ||
ROUND(MDPOS_RTL_OP1,2) || ';' ||
ROUND(MDPOS_RTL_RP1,2) || ';' ||
ROUND(OTB_CST_BUP1,2) || ';' ||
ROUND(OTB_CST_BUP2,2) || ';' ||
ROUND(OTB_CST_LP,2) || ';' ||
ROUND(OTB_CST_OP1,2) || ';' ||
ROUND(OTB_CST_RP1,2) || ';' ||
ROUND(OTB_UNT_BUP1,2) || ';' ||
ROUND(OTB_UNT_BUP2,2) || ';' ||
ROUND(OTB_UNT_LP,2) || ';' ||
ROUND(OTB_UNT_OP1,2) || ';' ||
ROUND(OTB_UNT_RP1,2) || ';' ||
ROUND(RECCOM_CST_BUP1,2) || ';' ||
ROUND(RECCOM_CST_BUP2,2) || ';' ||
ROUND(RECCOM_CST_LP,2) || ';' ||
ROUND(RECCOM_CST_OP1,2) || ';' ||
ROUND(RECCOM_CST_RP1,2) || ';' ||
ROUND(RECCOM_UNT_BUP1,2) || ';' ||
ROUND(RECCOM_UNT_BUP2,2) || ';' ||
ROUND(RECCOM_UNT_LP,2) || ';' ||
ROUND(RECCOM_UNT_OP1,2) || ';' ||
ROUND(RECCOM_UNT_RP1,2) || ';' ||
ROUND(RECNCOM_CST_BUP1,2) || ';' ||
ROUND(RECNCOM_CST_BUP2,2) || ';' ||
ROUND(RECNCOM_CST_LP,2) || ';' ||
ROUND(RECNCOM_CST_OP1,2) || ';' ||
ROUND(RECNCOM_CST_RP1,2) || ';' ||
ROUND(RECNCOM_UNT_BUP1,2) || ';' ||
ROUND(RECNCOM_UNT_BUP2,2) || ';' ||
ROUND(RECNCOM_UNT_LP,2) || ';' ||
ROUND(RECNCOM_UNT_OP1,2) || ';' ||
ROUND(RECNCOM_UNT_RP1,2) || ';' ||
ROUND(SHR_CST_BUP1,2) || ';' ||
ROUND(SHR_CST_BUP2,2) || ';' ||
ROUND(SHR_CST_LP,2) || ';' ||
ROUND(SHR_CST_OP1,2) || ';' ||
ROUND(SHR_CST_RP1,2) || ';' ||
ROUND(SHR_UNT_BUP1,2) || ';' ||
ROUND(SHR_UNT_BUP2,2) || ';' ||
ROUND(SHR_UNT_LP,2) || ';' ||
ROUND(SHR_UNT_OP1,2) || ';' ||
ROUND(SHR_UNT_RP1,2) || ';' ||
ROUND(SLSCON_CST_BUP1,2) || ';' ||
ROUND(SLSCON_CST_BUP2,2) || ';' ||
ROUND(SLSCON_CST_LP,2) || ';' ||
ROUND(SLSCON_CST_OP1,2) || ';' ||
ROUND(SLSCON_CST_RP1,2) || ';' ||
ROUND(SLSCON_RTL_BUP1,2) || ';' ||
ROUND(SLSCON_RTL_BUP2,2) || ';' ||
ROUND(SLSCON_RTL_LP,2) || ';' ||
ROUND(SLSCON_RTL_OP1,2) || ';' ||
ROUND(SLSCON_RTL_RP1,2) || ';' ||
ROUND(SLSCON_UNT_BUP1,2) || ';' ||
ROUND(SLSCON_UNT_BUP2,2) || ';' ||
ROUND(SLSCON_UNT_LP,2) || ';' ||
ROUND(SLSCON_UNT_OP1,2) || ';' ||
ROUND(SLSCON_UNT_RP1,2) || ';' ||
ROUND(SLSNXT_EXPC_BUP1,2) || ';' ||
ROUND(SLSNXT_EXPC_BUP2,2) || ';' ||
ROUND(SLSNXT_EXPC_LP,2) || ';' ||
ROUND(SLSNXT_EXPC_OP1,2) || ';' ||
ROUND(SLSNXT_EXPC_RP1,2) || ';' ||
ROUND(SLSNXT_EXPU_BUP1,2) || ';' ||
ROUND(SLSNXT_EXPU_BUP2,2) || ';' ||
ROUND(SLSNXT_EXPU_LP,2) || ';' ||
ROUND(SLSNXT_EXPU_OP1,2) || ';' ||
ROUND(SLSNXT_EXPU_RP1,2) || ';' ||
ROUND(SLS_CST_BUP1,2) || ';' ||
ROUND(SLS_CST_BUP2,2) || ';' ||
ROUND(SLS_CST_LP,2) || ';' ||
ROUND(SLS_CST_OP1,2) || ';' ||
ROUND(SLS_CST_RP1,2) || ';' ||
ROUND(SLS_RTL_BUP1,2) || ';' ||
ROUND(SLS_RTL_BUP2,2) || ';' ||
ROUND(SLS_RTL_LP,2) || ';' ||
ROUND(SLS_RTL_OP1,2) || ';' ||
ROUND(SLS_RTL_RP1,2) || ';' ||
ROUND(SLS_UNT_BUP1,2) || ';' ||
ROUND(SLS_UNT_BUP2,2) || ';' ||
ROUND(SLS_UNT_LP,2) || ';' ||
ROUND(SLS_UNT_OP1,2) || ';' ||
ROUND(SLS_UNT_RP1,2) || ';' ||
ROUND(SQM_BUP1,2) || ';' ||
ROUND(SQM_BUP2,2) || ';' ||
ROUND(SQM_LP,2) || ';' ||
ROUND(SQM_OP1,2) || ';' ||
ROUND(SQM_RP1,2) || '|'
FROM CA_PLAN_BUPP_VIEW;
SPOOL OFF;
EXIT;