SET HEADING OFF;
SET PAGESIZE 0;
SET WRAP OFF;
SET LINESIZE 10000;
SET TRIMSPOOL ON;
SET TRIMOUT ON;
SET TERMOUT OFF;
SET FEEDBACK OFF;
SPOOL .\FDEOutput\PLAN_MOPP_&&1..csv;
SELECT
'"' || CALENDAR || '";' ||
'"' || ORGANIZATION || '";' ||
'"' || PRODUCT || '";' ||
ROUND(ADJ_CST_MOP2,2) || ';' ||
ROUND(ADJ_CST_MOPP,2) || ';' ||
ROUND(ADJ_UNT_MOP2,2) || ';' ||
ROUND(ADJ_UNT_MOPP,2) || ';' ||
ROUND(BOP_CST_MOP2,2) || ';' ||
ROUND(BOP_CST_MOPP,2) || ';' ||
ROUND(BOP_UNT_MOP2,2) || ';' ||
ROUND(BOP_UNT_MOPP,2) || ';' ||
ROUND(CALBOP_CST_MOP2,2) || ';' ||
ROUND(CALBOP_CST_MOPP,2) || ';' ||
ROUND(CALBOP_UNT_MOP2,2) || ';' ||
ROUND(CALBOP_UNT_MOPP,2) || ';' ||
ROUND(CAOTB_CST_MOP2,2) || ';' ||
ROUND(CAOTB_CST_MOPP,2) || ';' ||
ROUND(CAOTB_UNT_MOP2,2) || ';' ||
ROUND(CAOTB_UNT_MOPP,2) || ';' ||
ROUND(FRT_CST_MOP2,2) || ';' ||
ROUND(FRT_CST_MOPP,2) || ';' ||
ROUND(MDPMD_RTL_MOP2,2) || ';' ||
ROUND(MDPMD_RTL_MOPP,2) || ';' ||
ROUND(MDPOS_RTL_MOP2,2) || ';' ||
ROUND(MDPOS_RTL_MOPP,2) || ';' ||
ROUND(OTB_CST_MOP2,2) || ';' ||
ROUND(OTB_CST_MOPP,2) || ';' ||
ROUND(OTB_UNT_MOP2,2) || ';' ||
ROUND(OTB_UNT_MOPP,2) || ';' ||
ROUND(RECCOM_CST_MOP2,2) || ';' ||
ROUND(RECCOM_CST_MOPP,2) || ';' ||
ROUND(RECCOM_UNT_MOP2,2) || ';' ||
ROUND(RECCOM_UNT_MOPP,2) || ';' ||
ROUND(RECNCOM_CST_MOP2,2) || ';' ||
ROUND(RECNCOM_CST_MOPP,2) || ';' ||
ROUND(RECNCOM_UNT_MOP2,2) || ';' ||
ROUND(RECNCOM_UNT_MOPP,2) || ';' ||
ROUND(SHR_CST_MOP2,2) || ';' ||
ROUND(SHR_CST_MOPP,2) || ';' ||
ROUND(SHR_UNT_MOP2,2) || ';' ||
ROUND(SHR_UNT_MOPP,2) || ';' ||
ROUND(SLSCON_CST_MOP2,2) || ';' ||
ROUND(SLSCON_CST_MOPP,2) || ';' ||
ROUND(SLSCON_RTL_MOP2,2) || ';' ||
ROUND(SLSCON_RTL_MOPP,2) || ';' ||
ROUND(SLSCON_UNT_MOP2,2) || ';' ||
ROUND(SLSCON_UNT_MOPP,2) || ';' ||
ROUND(SLSNXT_EXPC_MOP2,2) || ';' ||
ROUND(SLSNXT_EXPC_MOPP,2) || ';' ||
ROUND(SLSNXT_EXPU_MOP2,2) || ';' ||
ROUND(SLSNXT_EXPU_MOPP,2) || ';' ||
ROUND(SLS_CST_MOP2,2) || ';' ||
ROUND(SLS_CST_MOPP,2) || ';' ||
ROUND(SLS_RTL_MOP2,2) || ';' ||
ROUND(SLS_RTL_MOPP,2) || ';' ||
ROUND(SLS_UNT_MOP2,2) || ';' ||
ROUND(SLS_UNT_MOPP,2) || ';' ||
ROUND(SQM_MOP2,2) || ';' ||
ROUND(SQM_MOPP,2) || '|'
FROM CA_PLAN_MOPP_VIEW;
SPOOL OFF;
EXIT;